Repository arimger/Unity-Editor-Toolbox, pull requests merged in 2024-08, with the labels that each got.

#113 [Feature Request] Hierarchy Tree View #99
  Assets/Editor Toolbox/CHANGELOG.md
  Assets/Editor Toolbox/Editor/Hierarchy/HierarchyItemDataType.cs
  Assets/Editor Toolbox/Editor/Hierarchy/HierarchyPropertyLabel.cs
  Assets/Editor Toolbox/Editor/ToolboxEditorHierarchy.cs
  Assets/Editor Toolbox/Editor/ToolboxEditorSettings.cs
  README.md
Labels: enhancement

#114 Develop - 0.12.13
  Assets/Editor Toolbox/CHANGELOG.md
  Assets/Editor Toolbox/Editor/Drawers/Helpers/Extraction/ValueExtractionHelper.cs
  Assets/Editor Toolbox/Editor/Drawers/Toolbox/Condition/DisableInEditModeAttributeDrawer.cs
  Assets/Editor Toolbox/Editor/Drawers/Toolbox/Condition/DisableInEditModeAttributeDrawer.cs.meta
  Assets/Editor Toolbox/Editor/Hierarchy/HierarchyItemDataType.cs
  Assets/Editor Toolbox/Editor/Hierarchy/HierarchyPropertyLabel.cs
  Assets/Editor Toolbox/Editor/Hierarchy/HierarchyTreeUtility.cs
  Assets/Editor Toolbox/Editor/Hierarchy/HierarchyTreeUtility.cs.meta
  Assets/Editor Toolbox/Editor/ToolboxEditorHierarchy.cs
  Assets/Editor Toolbox/Editor/ToolboxEditorSettings.cs
  Assets/Editor Toolbox/Editor/ToolboxManager.cs
  Assets/Editor Toolbox/Editor/Utilities/PropertyUtility.cs
  Assets/Editor Toolbox/EditorSettings.asset
  Assets/Editor Toolbox/README.md
  Assets/Editor Toolbox/Runtime/Attributes/Property/Toolbox/ConditionAttributes/DisableInEditModeAttribute.cs
  Assets/Editor Toolbox/Runtime/Attributes/Property/Toolbox/ConditionAttributes/DisableInEditModeAttribute.cs.meta
  Assets/Editor Toolbox/package.json
  Assets/Examples/Scenes/SampleScene.unity
  Assets/Examples/Scripts/SampleBehaviour3.cs
  Docs/hierarchy.png
  Docs/hierarchy1.png
  Docs/hierarchy2.png
  README.md
Labels: bug, enhancement

#118 Develop - 0.13.1
  Assets/Editor Toolbox/CHANGELOG.md
  Assets/Editor Toolbox/Runtime/Serialization/SerializedDirectory.cs
  Assets/Editor Toolbox/package.json
Labels: bug

#119 Force standalone tests in the test.yml workflow
  .github/workflows/test.yml
Labels: test
